theme: jekyll-theme-slate
# baseurl : /accessibility-styleguide
# url: https://dhamaker.github.io/
exclude : [Gemfile, Gemfile.lock, _config.yml]
plugins:
#    - jekyll-feed
    - jekyll-sitemap

categories: [navigation, forms, media]
